<link rel="stylesheet" href="/admin/css/vendors/feather/feather.css" />
<link
  rel="stylesheet"
  href="/admin/css/vendors/ti-icons/css/themify-icons.css"
/>
<link rel="stylesheet" href="/admin/css/vendors/css/vendor.bundle.base.css" />
<link
  rel="stylesheet"
  href="/admin/css/vendors/datatables.net-bs4/dataTables.bootstrap4.css"
/>
<link
  rel="stylesheet"
  href="/admin/css/vendors/ti-icons/css/themify-icons.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="/admin/js/select.dataTables.min.css"
/>
<link rel="stylesheet" href="/admin/css/vertical-layout-light/style.css" />
<link rel="stylesheet" href="/admin/css/style.css" />
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
/>
<link
  rel="apple-touch-icon"
  sizes="57x57"
  href="/images/ico/apple-icon-57x57.png"
/>
<link
  rel="apple-touch-icon"
  sizes="60x60"
  href="/images/ico/apple-icon-60x60.png"
/>
<link
  rel="apple-touch-icon"
  sizes="72x72"
  href="/images/ico/apple-icon-72x72.png"
/>
<link
  rel="apple-touch-icon"
  sizes="76x76"
  href="/images/ico/apple-icon-76x76.png"
/>
<link
  rel="apple-touch-icon"
  sizes="114x114"
  href="/images/ico/apple-icon-114x114.png"
/>
<link
  rel="apple-touch-icon"
  sizes="120x120"
  href="/images/ico/apple-icon-120x120.png"
/>
<link
  rel="apple-touch-icon"
  sizes="144x144"
  href="/images/ico/apple-icon-144x144.png"
/>
<link
  rel="apple-touch-icon"
  sizes="152x152"
  href="/images/ico/apple-icon-152x152.png"
/>
<link
  rel="apple-touch-icon"
  sizes="180x180"
  href="/images/ico/apple-icon-180x180.png"
/>
<link
  rel="icon"
  type="image/png"
  sizes="192x192"
  href="/images/ico/android-icon-192x192.png"
/>
<link
  rel="icon"
  type="image/png"
  sizes="32x32"
  href="/images/ico/favicon-32x32.png"
/>
<link
  rel="icon"
  type="image/png"
  sizes="96x96"
  href="/images/ico/favicon-96x96.png"
/>
<link
  rel="icon"
  type="image/png"
  sizes="16x16"
  href="/images/ico/favicon-16x16.png"
/>
<link rel="manifest" href="/images/ico/manifest.json" />
<meta name="msapplication-TileColor" content="#ffffff" />
<meta
  name="msapplication-TileImage"
  content="/images/ico/ms-icon-144x144.png"
/>
<meta name="theme-color" content="#ffffff" />
